### ISSUE TITLE
Consider better view for endpoint selection

### ISSUE THREAD

**Issue by gagath** [Vrong/ovh_mail_redirections_manager_for_android#2]
Selection of endpoint is a choice in the list mentionned in the README.

It would be great if the user could select the endpoint from a list widget rather than from knowing he has to enter something like "ovh-eu". My two cents.

**Comment by Vrong** [comment]
Yes I know about this improvement. However, this functionality was not essential during the early development, and my ass was too lazy to implement it later. 
Thanks for pointing the issue, you are free to patch and submit your pull request; and making it easier for the users.

**Comment by Vrong** [comment]
The feature has been added with 39c32a620653d8b377d8e09d5d0a3b3dafa28142
