### ISSUE TITLE
Minimum SDK set to 15 but checking if SDK > 15 in code

### ISSUE THREAD

**Issue by gagath** [Vrong/ovh_mail_redirections_manager_for_android#4]
Almost everything in the title.

The checks in `LoginActivity.java` for the `showProgress` method are marked as useless by Android Studio because you check SDK > 15 but minSDK is already set for 15. This warning applies for the `@TargetApi(Build.VERSION_CODES.HONEYCOMB_MR2)` and `if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB_MR2)` code.

Proposed solution is either support SDK < 15 (not sure this is what we want) or remove the not needed checks.

**Comment by Vrong** [comment]
This is part of the auto-generated code, I will take a look whenever I've got time.

**Comment by Vrong** [comment]
I've taken a look into the issue. This guarantees that the application will still work if run under SDK 15, however as you stated the minimum SDK is set to 15 so it should not happen. Nevertheless this part of code indicates the compatibility level of the wrapped code. This does not make sense on a project point of view but it does on a local one. It's part of the LoginActivity complete behaviour and makes it would still work if ported to a lower SDK level. (for whatever reason, by any contributor of forker)
There can be a debate on this, but there is not point as this piece of code doesn't cause any harm.

**Comment by gagath** [comment]
Ok, seems fair to me.
